[connections.supabase]
SUPABASE_URL = "https://osyigahgtuexzdpdvmdc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zeWlnYWhndHVleHpkcGR2bWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU2NzU1MzcsImV4cCI6MjAzMTI1MTUzN30.GrNhO9Kch1kidRQ_4SibPC802G5P8rNQYcPopPV6VW8"